# Generated by Django 3.2.8 on 2021-10-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deparment',
            options={'ordering': ('name',), 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
    ]
